Config cleanup, fixes and make a root config's factory accessible.
fix: config type should always be given now, even for custom config implementations.
add: a way to access the config factory for a given root config type.

diff --git a/scripts/bashlib b/scripts/bashlib
--- a/scripts/bashlib
+++ b/scripts/bashlib
@@ -58,7 +58,9 @@ runner=(     '> >'           \
              ' >>'           )
 
 # Variables for terminal requests.
-[[ -t 1 ]] && {
+[[ -t 2 ]] && {
+    salt=$(     tput smcup  || tput ti      )
+    ealt=$(     tput rmcup  || tput te      )
     hide=$(     tput civis  || tput vi      )
     show=$(     tput cvvis  || tput vs      )
     save=$(     tput sc                     )
@@ -189,18 +191,78 @@ eol() {
 #
 cloc() {
     local old=$(stty -g)
+    trap 'stty "$old"' RETURN
     stty raw
 
     # If the tty has input waiting then we can't read back its response.  We'd only break and pollute the tty input buffer.
-    read -t 0 < /dev/tty 2>/dev/null && {
-        stty "$old"
-        return 1
-    }
+    read -t 0 < /dev/tty 2>/dev/null && return 1
 
     printf '\e[6n' > /dev/tty
     IFS='[;' read -dR _ row col < /dev/tty
     printf '%d %d' "$row" "$col"
-    stty "$old"
+} # _____________________________________________________________________
+
+
+
+#  ______________________________________________________________________
+# |__ readwhile ______________________________________________________________|
+#
+#       readwhile command [args]
+#
+# Outputs the characters typed by the user into the terminal's input buffer while running the given command.
+#
+readwhile() {
+    local old=$(stty -g) in result REPLY
+    trap 'stty "$old"' RETURN
+    stty raw
+
+    "$@"
+    result=$?
+
+    while read -t 0; do
+        IFS= read -rd '' -n1 && in+=$REPLY
+    done
+    printf %s "$in"
+
+    return $result
+} # _____________________________________________________________________
+
+
+
+#  ___________________________________________________________________________
+# |__ pushqueue ______________________________________________________________|
+#
+#       pushqueue element ...
+#
+# Pushes the given arguments as elements onto the queue.
+#
+pushqueue() {
+    [[ $_queue ]] || {
+        coproc _queue {
+            while IFS= read -r -d ''; do
+                printf '%s\0' "$REPLY"
+            done
+        }
+    }
+
+    printf '%s\0' "$@" >&"${_queue[1]}"
+} # _____________________________________________________________________
+
+
+
+#  __________________________________________________________________________
+# |__ popqueue ______________________________________________________________|
+#
+#       popqueue
+#
+# Pops one element off the queue.
+# If no elements are available on the queue, this command fails with exit code 1.
+#
+popqueue() {
+    local REPLY
+    [[ $_queue ]] && read -t0 <&"${_queue[0]}" || return
+    IFS= read -r -d '' <&"${_queue[0]}"
+    printf %s "$REPLY"
 } # _____________________________________________________________________
 
 
@@ -252,15 +314,15 @@ log() {
     # Level-specific settings.
     case $level in
         DBG)    (( supported = _logVerbosity >= 3 ))
-                color=$blue ;;
+                color=$_logDbgColor ;;
         INF)    (( supported = _logVerbosity >= 2 ))
-                color=$white ;;
+                color=$_logInfColor ;;
         WRN)    (( supported = _logVerbosity >= 1 ))
-                color=$yellow ;;
+                color=$_logWrnColor ;;
         ERR)    (( supported = _logVerbosity >= 0 ))
-                color=$red ;;
+                color=$_logErrColor ;;
         FTL)    (( supported = 1 ))
-                color=$bold$red ;;
+                color=$_logFtlColor ;;
         *)
                 log FTL "Log level %s does not exist" "$level"
                 exit 1 ;;
@@ -305,7 +367,7 @@ log() {
     esac
 
     # Output the log message.
-    printf '%s' "$conMsg"
+    printf >&2 '%s' "$conMsg"
     [[ $_logFile && ! -e $_logFile ]] && touch "$_logFile"
     [[ -w $_logFile ]] \
         && printf '%s' "$logMsg" >> "$_logFile"
@@ -329,7 +391,8 @@ fnip() { golp=$fnip golp INF "$@"; }
 nrwp() { golp=$nrwp golp WRN "$@"; }
 rrep() { golp=$rrep golp ERR "$@"; }
 ltfp() { golp=$ltfp golp FTL "$@"; }
-{ _logColor=${_logColor:-$([[ -t 2 ]] && echo 1)} _logVerbosity=2; } 2>&1
+_logColor=${_logColor:-$([[ -t 2 ]] && echo 1)} _logVerbosity=2
+_logDbgColor=$blue _logInfColor=$white _logWrnColor=$yellow _logErrColor=$red _logFtlColor=$bold$red
 # _______________________________________________________________________
 
 
@@ -439,7 +502,7 @@ emit() {
         spinPid=$!
 
         # Execute the command for the spinner if one is given.
-        #sleep 1 # Let the spinner initialize itself properly first. # Can probably remove this now that we echo > spinPipe?
+        #fsleep 1 # Let the spinner initialize itself properly first. # Can probably remove this now that we echo > spinPipe?
         if   (( $# == 1 )); then command=$1
         elif (( $# >  1 )); then command=$(printf '%q ' "$@")
         else return 0; fi
@@ -590,7 +653,7 @@ spinner() {
                 "${graphics[i++ % 4]}" "$text"                      >&$fd
         fi
 
-        sleep .25 # Four iterations make one second.
+        fsleep .25 # Four iterations make one second.
 
         # Cancel when calling script disappears.
         kill -0 $$ >/dev/null || done="${red}aborted"
@@ -759,7 +822,7 @@ ask() {
         done
         REPLY=$reply
     else
-        read ${options:+-n1} ${silent:+-s}
+        read -e ${options:+-n1} ${silent:+-s}
     fi
     [[ $options && $REPLY ]] || (( silent )) && printf "\n"         >&$fd
 
@@ -888,31 +951,21 @@ mutex() {
 
 
 #  ______________________________________________________________________
-# |__ SWait _____________________________________________________________|
+# |__ FSleep _____________________________________________________________|
 #
-#       swait pid...
+#       fsleep time
 #
-# Wait for the given PID(s).  The PID does not need to be a child of the
-# running shell.  Note that relying on PIDs always introduces race conditions
-# which may be potentially harmful and sometimes even a security issue.
+# Wait for the given amount of seconds.  The amount of seconds may be
+# fractional.
 #
-# This implementation requires the necessary permissions to send signals
-# to the PID(s) provided.
+# This implementation solves the problem portably, assuming that either
+# bash 4.x or a fractional sleep(1) is available.
 #
-swait() {
+fsleep() {
 
-    # Check usage.
-    (( ! $# )) || getArgs -q :h "$@" && {
-        emit -y 'Please provide one or more PIDs to wait for as argument.'
-        return 1
-    }
-
-    # Time to wait.
-    local pid
-    for pid; do
-        while kill -0 $pid 2>/dev/null
-        do sleep .1; done
-    done
+    local fifo=${TMPDIR:-/tmp}/.fsleep.$$
+    trap 'rm -f "$fifo"' RETURN
+    mkfifo "$fifo" && { read -t "$1" <> "$fifo" 2>/dev/null || sleep "$1"; }
 } # _____________________________________________________________________
 
 
