scripts update

diff --git a/scripts/mvn-release b/scripts/mvn-release
--- a/scripts/mvn-release
+++ b/scripts/mvn-release
@@ -22,7 +22,12 @@
 #   * http://lhunath.lyndir.com                                               #
 #   * Maarten Billemont.                                                      #
 #                                                                             #
-source mvn-tools || exit
+
+#source mvn-tools || exit
+set -e
+trap 'echo "$BASH_SOURCE:$BASH_LINENO: ${FUNCNAME:+$FUNCNAME:}$BASH_COMMAND failed with exit code: $?"' ERR
+[[ $0 = */* && -e ${0%/*}/bashlib ]] && source "${0%/*}/bashlib" || source bashlib
+
 cd "$root"
 
 
@@ -69,6 +74,10 @@ while getopts :pbh arg; do
 done
 shift $((OPTIND-1))
 
+releaseProfile="release"
+
+emit "Release profile: -P$releaseProfile"
+
 # Ask for the to-be-released version number.
 while true; do
     [[ $version ]] || version=$1
@@ -77,17 +86,14 @@ while true; do
     until version=$(ask "Which version are you releasing? [$version] " || echo "$version") && [[ $version ]]
     do true; done
 
+    emit "Version: $version"
+
     if (( prepare )) && [[ $(git tag -l "$version") ]]; then
         emit -r "Version '$version' is already tagged."
     else
         break
     fi
 done
-if [[ $(git symbolic-ref -q HEAD) = *-maint || $version = *-p* ]]; then
-    ask -y!N "Create a maintenance branch?" && maintBranch=1
-else
-    ask -Y!n "Create a maintenance branch?" && maintBranch=1
-fi
 
 # Prepare the release by updating versions and tagging in SCM.
 if (( prepare )); then
@@ -97,12 +103,12 @@ if (( prepare )); then
 
     emit "Updating Maven and GIT for the release of $version"
     if (( releasePom )); then
-        mvn -Prelease --batch-mode $cleanRelease release:prepare-with-pom -DpushChanges=false -Dtag="$version" -DreleaseVersion="$version" ||:
+        mvn -P$releaseProfile --batch-mode $cleanRelease release:prepare-with-pom -DpushChanges=false -Dtag="$version" -DreleaseVersion="$version" ||:
         # Workaround for <http://jira.codehaus.org/browse/MRELEASE-539> -- Let normal release:prepare finish it off.
         git commit -vF <(echo '[maven-release-plugin] [workaround] release cleanup')
-        mvn -Prelease release:prepare -DpushChanges=false
+        mvn -P$releaseProfile release:prepare -DpushChanges=false
     else
-        mvn -Prelease --batch-mode $cleanRelease release:prepare -DpushChanges=false -Dtag="$version" -DreleaseVersion="$version"
+        mvn -P$releaseProfile --batch-mode $cleanRelease release:prepare -DpushChanges=false -Dtag="$version" -DreleaseVersion="$version"
     fi
 fi
 step=1
@@ -118,34 +124,12 @@ if (( perform )); then
     emit "Deploying the code for the release of $version"
     if (( releasePom )); then
         # Workaround for <http://jira.codehaus.org/browse/MRELEASE-542> -- Force use of release-pom.xml
-        mvn -Prelease release:perform -DpushChanges=true -D"arguments=-Prelease -f release-pom.xml"
+        mvn -P$releaseProfile release:perform -DpushChanges=true -D"arguments=-P$releaseProfile -f release-pom.xml"
     else
-        mvn -Prelease release:perform -DpushChanges=true -D"arguments=-Prelease" -Dtag="$version"
+        mvn -P$releaseProfile release:perform -DpushChanges=true -D"arguments=-P$releaseProfile" -Dtag="$version"
     fi
     git push && git push --tags
 fi
 step=2
-
-# Create the release's maintenance branch.
-if (( branch && maintBranch )); then
-    # Remember where we came from so we can come back.
-    emit "Making a maintenance branch for the release of $version"
-    if ! before=$(git symbolic-ref -q HEAD); then
-        before="_before-rel"
-        git tag "$before"
-        trap 'git tag -d "$before"' EXIT
-    fi
-
-    # Create a fake branch because release:branch fails when not on a branch.
-    git checkout -b "_$version-rel" "$version"
-
-    mvn -Prelease --batch-mode release:branch -DreleaseVersion=GIT-SNAPSHOT
-
-    # Go back to where we came from.
-    git checkout "${before##refs/heads/}"
-
-    # Clean up fake branch.
-    git branch -D "_$version-rel"
-fi
 
 emit "All done."
